version: '3.3'

services:

  squid:
    container_name: 'vulnerable'
    hostname: 'vulnerable'
    # image: 'minimum2scp/squid'
    image: 'sameersbn/squid'
    # network_mode: bridge
    ports:
      - '3128:3128'
      - '3129:3129'
    volumes:
      # - "$PWD/source/squid.conf:/etc/squid/squid.conf:ro"
      - "$PWD/source/ERR_CERT_AUTHORITY_INVALID:/etc/squid/errors/ERR_CERT_AUTHORITY_INVALID:ro"
      - "$PWD/key.pem:/key.pem:ro"
      - "$PWD/cert.pem:/cert.pem:ro"