version: '3.3'

networks:
  every:
    external: false

services:

  squid:
    build: .
    container_name: 'vulnerable'
    hostname: 'vulnerable'
    # Version 3.5.27 built with --with-openssl is vulnerable. 3.5.28 is not.
    # image: 'sameersbn/squid:3.5.27'
    networks:
      - every
    ports:
      - '3128:3128'
      - '3129:3129'
    volumes:
      - "$PWD/source/squid.conf:/etc/squid/squid.conf:ro"
      # I don't think these next two volumes are actually needed...
      - "$PWD/source/ERR_CERT_AUTHORITY_INVALID:/etc/squid/errors/ERR_CERT_AUTHORITY_INVALID:ro"
      - "$PWD/source/ERR_ACCESS_DENIED:/etc/squid/errors/ERR_ACCESS_DENIED:ro"
      - "$PWD/key.pem:/key.pem:ro"
      - "$PWD/cert.pem:/cert.pem:ro"

  web:
    container_name: 'malicious'
    hostname: 'malicious'
    image: 'nginx:latest'
    networks:
      - every
    volumes:
      - "$PWD/source/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "$PWD/source/index.html:/usr/share/nginx/html/index.html:ro"
      - "$PWD/key.pem:/key.pem:ro"
      - "$PWD/cert.pem:/cert.pem:ro"